services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
  
  adminer: 
    image: adminer
    restart: always
    ports:
      - "4567:8080"
    links:
      - postgres